// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ1o7RAfBzFacxfpA3NR9TQQcPI4ezF3Q',
    appId: '1:940128216104:web:1e35676737268568d3411d',
    messagingSenderId: '940128216104',
    projectId: 'garden--carnation',
    authDomain: 'garden--carnation.firebaseapp.com',
    databaseURL: 'https://garden--carnation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garden--carnation.appspot.com',
    measurementId: 'G-6C7FQJ5D71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPCseHcAey7RfIh9HzLZyoJCJ6o9as1cQ',
    appId: '1:940128216104:android:287630439bb808ddd3411d',
    messagingSenderId: '940128216104',
    projectId: 'garden--carnation',
    databaseURL: 'https://garden--carnation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garden--carnation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGMqutY55ZzqFGNRaQkwbtWImqEyhVHw',
    appId: '1:940128216104:ios:6f33c4d5828d6b7cd3411d',
    messagingSenderId: '940128216104',
    projectId: 'garden--carnation',
    databaseURL: 'https://garden--carnation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garden--carnation.appspot.com',
    iosBundleId: 'com.example.carnation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGMqutY55ZzqFGNRaQkwbtWImqEyhVHw',
    appId: '1:940128216104:ios:de84d8356555f1acd3411d',
    messagingSenderId: '940128216104',
    projectId: 'garden--carnation',
    databaseURL: 'https://garden--carnation-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garden--carnation.appspot.com',
    iosBundleId: 'com.example.carnation.RunnerTests',
  );
}
